In [1]:
import numpy as np

In [2]:
a = np.arange(12)

In [3]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
a.ndim

1

In [5]:
a1 = a.reshape(4,3)

In [6]:
a1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [7]:
a1.ndim

2

In [8]:
a2 = a.reshape(2,3,2)

In [9]:
a2

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [10]:
a2.ndim

3