In [ ]:
pip install numpy

In [ ]:
import numpy as np

In [ ]:
a = np.array([2, 8, 4, 7])
type(a)

numpy.ndarray

In [ ]:
a.dtype

dtype('int64')

In [ ]:
a.ndim

1

In [ ]:
a.max()

8

In [ ]:
a.min()

2

In [ ]:
a.itemsize

8

In [ ]:
a.size

4

In [ ]:
len(a)

4

In [ ]:
a.sum()

21

# 1D Array

Different ways to create 1D array

In [ ]:
a1 = np.array([1,5,8,9,6.5], dtype="int")

In [ ]:
a1

array([1, 5, 8, 9, 6])

In [ ]:
type(a1)

numpy.ndarray

In [ ]:
a1.dtype

dtype('int64')

In [ ]:
a2 = np.array([1,5,8,9,6.5,'abc'])

In [ ]:
a2

array(['1', '5', '8', '9', '6.5', 'abc'], dtype='<U32')

In [ ]:
type(a2)

numpy.ndarray

In [ ]:
a2.dtype

dtype('<U32')

In [ ]:
a2 = np.arange(1,9,3)

In [ ]:
a2

array([1, 4, 7])

In [ ]:
a3 = np.arange(45,60,3)

In [ ]:
a3

array([45, 48, 51, 54, 57])

In [ ]:
a3.dtype

dtype('int64')

In [ ]:
a4 = np.arange(4,9,0.47)

In [ ]:
a4

array([4.  , 4.47, 4.94, 5.41, 5.88, 6.35, 6.82, 7.29, 7.76, 8.23, 8.7 ])

In [ ]:
a4.size

11

linspace(start, stop, no.of element)

In [ ]:
a1 = np.linspace(4,9,12)

In [ ]:
a1

array([4.        , 4.45454545, 4.90909091, 5.36363636, 5.81818182,
       6.27272727, 6.72727273, 7.18181818, 7.63636364, 8.09090909,
       8.54545455, 9.        ])

In [ ]:
np.linspace(4,10)

array([ 4.        ,  4.12244898,  4.24489796,  4.36734694,  4.48979592,
        4.6122449 ,  4.73469388,  4.85714286,  4.97959184,  5.10204082,
        5.2244898 ,  5.34693878,  5.46938776,  5.59183673,  5.71428571,
        5.83673469,  5.95918367,  6.08163265,  6.20408163,  6.32653061,
        6.44897959,  6.57142857,  6.69387755,  6.81632653,  6.93877551,
        7.06122449,  7.18367347,  7.30612245,  7.42857143,  7.55102041,
        7.67346939,  7.79591837,  7.91836735,  8.04081633,  8.16326531,
        8.28571429,  8.40816327,  8.53061224,  8.65306122,  8.7755102 ,
        8.89795918,  9.02040816,  9.14285714,  9.26530612,  9.3877551 ,
        9.51020408,  9.63265306,  9.75510204,  9.87755102, 10.        ])

logspace(start, stop, no.of elements)

In [ ]:
np.logspace(1,5,5)

array([1.e+01, 1.e+02, 1.e+03, 1.e+04, 1.e+05])

In [ ]:
np.logspace(1,5)

array([1.00000000e+01, 1.20679264e+01, 1.45634848e+01, 1.75751062e+01,
       2.12095089e+01, 2.55954792e+01, 3.08884360e+01, 3.72759372e+01,
       4.49843267e+01, 5.42867544e+01, 6.55128557e+01, 7.90604321e+01,
       9.54095476e+01, 1.15139540e+02, 1.38949549e+02, 1.67683294e+02,
       2.02358965e+02, 2.44205309e+02, 2.94705170e+02, 3.55648031e+02,
       4.29193426e+02, 5.17947468e+02, 6.25055193e+02, 7.54312006e+02,
       9.10298178e+02, 1.09854114e+03, 1.32571137e+03, 1.59985872e+03,
       1.93069773e+03, 2.32995181e+03, 2.81176870e+03, 3.39322177e+03,
       4.09491506e+03, 4.94171336e+03, 5.96362332e+03, 7.19685673e+03,
       8.68511374e+03, 1.04811313e+04, 1.26485522e+04, 1.52641797e+04,
       1.84206997e+04, 2.22299648e+04, 2.68269580e+04, 3.23745754e+04,
       3.90693994e+04, 4.71486636e+04, 5.68986603e+04, 6.86648845e+04,
       8.28642773e+04, 1.00000000e+05])

zeros()

In [ ]:
np.zeros(5,dtype="int")

array([0, 0, 0, 0, 0])

In [ ]:
np.ones(7,dtype="int")

array([1, 1, 1, 1, 1, 1, 1])

In [ ]:
a

array([2, 8, 4, 7])

In [ ]:
a[0]

2

In [ ]:
a[-1]

7

In [ ]:
a[1:3]

array([8, 4])

In [ ]:
a[::2]

array([2, 4])

2D Array
Collection of 1D

In [ ]:
a = np.array([[11,22,33,44],[55,66,77,88]])

In [ ]:
a

array([[11, 22, 33, 44],
       [55, 66, 77, 88]])

In [ ]:
a.ndim

2

In [ ]:
a[0].ndim

1

In [ ]:
a[-1]

array([55, 66, 77, 88])

In [ ]:
a[1][1:3]

array([66, 77])

In [ ]:
a[1][1] #indexing (extracting in static form)

66

In [ ]:
a[1][1:2] #slicing (extracting in 1d form)

array([66])

In [ ]:
a[1:2,1:2] #extrating in 2d form

array([[66]])

In [ ]:
a[0:2:1,1:3:1]

array([[22, 33],
       [66, 77]])

In [ ]:
a[::2,::3]

array([[11, 44]])

In [ ]:
a

array([[11, 22, 33, 44],
       [55, 66, 77, 88]])

In [ ]:
a.shape

(2, 4)

In [ ]:
a.ravel() #conversion of 2d to 1d array

array([11, 22, 33, 44, 55, 66, 77, 88])

In [ ]:
a.size

8

In [ ]:
len(a)

2

In [ ]:
a.reshape(4,2)

array([[11, 22],
       [33, 44],
       [55, 66],
       [77, 88]])

In [ ]:
a.reshape(8,1)

array([[11],
       [22],
       [33],
       [44],
       [55],
       [66],
       [77],
       [88]])

Different ways to create 2d array using arange() func

In [ ]:
np.arange(8).reshape(4,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [ ]:
np.linspace(1,11,20).reshape(5,4)

array([[ 1.        ,  1.52631579,  2.05263158,  2.57894737],
       [ 3.10526316,  3.63157895,  4.15789474,  4.68421053],
       [ 5.21052632,  5.73684211,  6.26315789,  6.78947368],
       [ 7.31578947,  7.84210526,  8.36842105,  8.89473684],
       [ 9.42105263,  9.94736842, 10.47368421, 11.        ]])

3d array (collection of 2d array)

In [ ]:
b = np.array([[[5,2,8,7],[5,8,7,9]],[[5,7,9,1],[4,7,2,1]]])

In [ ]:
b

array([[[5, 2, 8, 7],
        [5, 8, 7, 9]],

       [[5, 7, 9, 1],
        [4, 7, 2, 1]]])

In [ ]:
b.shape

(2, 2, 4)

In [ ]:
b.ndim

3

In [ ]:
b[:]

array([[[5, 2, 8, 7],
        [5, 8, 7, 9]],

       [[5, 7, 9, 1],
        [4, 7, 2, 1]]])

In [ ]:
b[1][0:1,1:3]

array([[7, 9]])

In [ ]:
b[1:2,0:1,1:3]

array([[[7, 9]]])

In [ ]:
b[0]

array([[5, 2, 8, 7],
       [5, 8, 7, 9]])

In [ ]:
b[1]

array([[5, 7, 9, 1],
       [4, 7, 2, 1]])

In [ ]:
b[:,1:2,::3]

array([[[5, 9]],

       [[4, 1]]])

In [ ]:
a = np.arange(30).reshape(3,2,5)

In [ ]:
a

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [ ]:
a.ndim

3

In [ ]:
a.shape

(3, 2, 5)

In [ ]:
a.reshape(3,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])